export * from './general.interface'
export * from './resource.interface'
export * from './schema.interface'
export * from './simpli.interface'
export * from './socket.interface'
export * from './vendor.interface'
