export * from './axios.interface'
export * from './collection.interface'
export * from './general.interface'
export * from './resource.interface'
export * from './schema.interface'
export * from './simpli.interface'
export * from './socket.interface'
export * from './validator.interface'
